[workspace]
name = "jupyterlite-build"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64"]

[dependencies]
python = ">=3.12"

[pypi-dependencies]
jupyterlite-core = "*"
jupyterlite-pyodide-kernel = "*"
jupyterlab = "*"

[tasks]
build = "jupyter lite build --output-dir /build/output"
